services:
  setupcicd:
    build:
      context: ./SetupCiCd
    container_name: setupcicd
    ports:
      - "5010:8080"
  
  postgresql:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
